apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: 'vmxfp-app-secrets'
  namespace: vmxfp-app
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: openai-credentials
        objectType: secretsmanager
        jmesPath:
          - path: api_key
            objectAlias: openai_api_key

      - objectName: "/vmxfp-app/dev/database/ro-endpoint"
        objectType: ssmparameter
        objectAlias: vmxfp-app-database-ro-host

      - objectName: vmxfp-app-database-secret-dev
        objectAlias: vmxfp-app-database-secret
        objectType: secretsmanager
        jmesPath:
          - path: host
            objectAlias: host
          - path: to_string(port)
            objectAlias: port
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
          - path: dbname
            objectAlias: dbname

  secretObjects:
    - secretName: 'openai-credentials'
      type: Opaque
      data:
        - objectName: 'openai_api_key'
          key: 'api_key'

    - secretName: 'vmxfp-app-database-ro-host'
      type: Opaque
      data:
        - objectName: 'vmxfp-app-database-ro-host'
          key: 'vmxfp-app-database-ro-host'

    - secretName: 'vmxfp-app-database-secret'
      type: Opaque
      data:
        - objectName: 'host'
          key: 'host'
        - objectName: 'port'
          key: 'port'
        - objectName: 'username'
          key: 'username'
        - objectName: 'password'
          key: 'password'
        - objectName: 'dbname'
          key: 'dbname'
