apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: 'vmxfp-vmx-secrets'
  namespace: vmxfp-app
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: vmx-credentials
        objectType: secretsmanager
        jmesPath:
          - path: domain
            objectAlias: domain
          - path: api_key
            objectAlias: vmx_api_key
          - path: workspace_id
            objectAlias: workspace_id
          - path: environment_id
            objectAlias: environment_id
          - path: resource_id
            objectAlias: resource_id

  secretObjects:
    - secretName: 'vmx-credentials'
      type: Opaque
      data:
        - objectName: 'domain'
          key: 'domain'
        - objectName: 'vmx_api_key'
          key: 'api_key'
        - objectName: 'workspace_id'
          key: 'workspace_id'
        - objectName: 'environment_id'
          key: 'environment_id'
        - objectName: 'resource_id'
          key: 'resource_id'
