apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://go.temporal.io/helm-charts
    chart: temporal
    targetRevision: 0.63.0
    helm:
      releaseName: temporal
      values: |
        prometheus:
          enabled: false
        grafana:
          enabled: false
        server:
          replicaCount: 1
          config:
            namespaces:
              create: true
              namespace:
                - name: default
                  retention: 180d
        elasticsearch:
          replicas: 1
        cassandra:
          config:
            cluster_size: 1
        ui:
          enabled: true
        web:
          additionalEnv:
            - name: TEMPORAL_UI_PUBLIC_PATH
              value: /temporal
            - name: TEMPORAL_CSRF_COOKIE_INSECURE
              value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
