name: dm-infra

version: '3.5'
services:
  localstack:
    image: localstack/localstack
    networks:
      - infra-network
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      AWS_DEFAULT_REGION: us-east-1
      SERVICES: s3,kms,iam,sts,sns,cloudformation,lambda,ssm,events
      TEST_AWS_ACCOUNT_ID: '000000000000'
      SKIP_SSL_CERT_DOWNLOAD: 1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  infra-network:
    driver: bridge
    name: infra-network
