[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [ "ingestion-workflow", "utils" ]

[tool.uv.workspace]
members = [ "packages/libs/utils", "packages/workflows/ingestion" ]

[tool.uv.sources.ingestion-workflow]
workspace = true

[tool.uv.sources.utils]
workspace = true

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1"
]
