[tool.coverage.run]
branch = true
source = [ "workflow_worker" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../../coverage/packages/workflows/ingestion/html'
 --cov-report xml:'../../../coverage/packages/workflows/ingestion/coverage.xml'
 --html='../../../reports/packages/workflows/ingestion/unittests/html/index.html'
 --junitxml='../../../reports/packages/workflows/ingestion/unittests/junit.xml'
"""

[tool.hatch.build.targets.wheel]
packages = [ "workflow_worker" ]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ "B008" ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[tool.uv.sources]
vmxfp-py-utils = { workspace = true }
vmxfp-py-db-models = { workspace = true }
vmxfp-py-db-repositories = { workspace = true }
vmxfp-py-services = { workspace = true }
vmxfp-py-db-services = { workspace = true }
vmxfp-py-temporal-utils = { workspace = true }
vmxfp-py-logger = { workspace = true }
vmxfp-py-schemas = { workspace = true }
workflow-ingestion = { workspace = true }
evaluation-workflow = { workspace = true }

[project]
name = "workflow-worker"
version = "1.0.0"
description = "Automatically generated by Nx."
requires-python = ">=3.9,<4"
readme = "README.md"
dependencies = [
 "aioboto3>=14.3.0",
 "dependency-injector>=4.46.0",
 "langchain-community>=0.3.24",
 "langchain-openai>=0.3.16",
 "langchain-text-splitters>=0.3.8",
 "pdf2image>=1.17.0",
 "pypdf>=5.5.0",
 "temporalio>=1.11.1",
 "tiktoken>=0.9.0",
 "vmxfp-py-utils",
 "vm-x-ai-sdk==1.6.2",
 "vmxfp-py-db-models",
 "vmxfp-py-db-repositories",
 "vmxfp-py-services",
 "vmxfp-py-db-services",
 "vmxfp-py-temporal-utils",
 "vmxfp-py-logger",
 "vmxfp-py-schemas",
 "workflow-ingestion",
 "evaluation-workflow",
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"
