"""add status embedding

Revision ID: 018b3ae8670a
Revises: 383bff3555c9
Create Date: 2025-05-27 09:27:27.126905

"""

from collections.abc import Sequence
from typing import Union

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "018b3ae8670a"
down_revision: Union[str, None] = "383bff3555c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE fileembeddingstatus AS ENUM ('CHUNKED', 'EMBEDDED')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_embeddings",
        sa.Column(
            "status",
            sa.Enum("CHUNKED", "EMBEDDED", name="fileembeddingstatus"),
            nullable=True,
        ),
    )

    op.execute(
        sa.text("""
            UPDATE file_embeddings
            SET status = 'CHUNKED'
            WHERE status IS NULL
        """)
    )

    op.alter_column(
        "file_embeddings",
        "status",
        nullable=False,
    )

    op.alter_column(
        "file_embeddings",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file_embeddings",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    op.drop_column("file_embeddings", "status")
    # ### end Alembic commands ###
