name: Set Up GitHub App
description: Set up GitHub App

inputs:
  app-id:
    description: 'The GitHub App ID'
    required: true
    type: string
  private-key:
    description: 'The private key for the GitHub App'
    required: true
    type: string

outputs:
  token:
    description: 'The GitHub token'
    value: ${{ steps.generate_token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.generate_token.outputs.token }}

    - uses: ./.github/actions/setup-monorepo

    - name: Git config
      shell: bash
      run: |
        git config user.name "my_awesome[bot]"
        git config user.email "<APP_ID>+my_awesome[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git
