apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.resourcePrefix }}-api"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: "{{ .Values.resourcePrefix }}-api"
  ports:
    - port: "{{ .Values.service.port }}"
      targetPort: "{{ .Values.service.targetPort }}"
  type: "{{ .Values.service.type }}"
