name: vmxfp-app

services:
  vmxfp-app-postgresql:
    container_name: vmxfp-app-postgresql
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: ingestion
    image: ankane/pgvector
    networks:
      - app-network
    ports:
      - '5433:5432'
    expose:
      - 5433
    volumes:
      - /var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
    name: app-network
