kms:
  arn: !cf_output secrets-kms-dev.KeyArn
parameters: []
secrets:
  - name: openai-credentials
    description: OpenAI credentials
  - name: vmx-credentials
    description: VMX credentials
  - name: file-processing-app-database-secret-dev
    description: Database secret
secrets_file: ./_encrypted/dev.yaml
