kms:
  arn: !cf_output secrets-kms-dev.KeyArn
parameters: []
secrets:
  - name: argocd-github-token
    description: GitHub token for ArgoCD
  - name: openai-credentials
    description: OpenAI credentials
  - name: vmx-credentials
    description: VMX credentials
secrets_file: ./_encrypted/dev.yaml
