image:
  repository: '{{ .Values.sharedServicesAccountId }}.dkr.ecr.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.resourcePrefix }}-ui-ecr-shared'
  tag: dev-latest
  # Update to IfNotPresent when using proper image tags
  pullPolicy: Always
env:
  vmxCredentialsSecret: vmx-credentials
resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 500m
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
namespace: {{ .Values.resourcePrefix }}-app
